// File generated by helping assistant.
// Please replace the placeholders with your actual Firebase configuration keys.
// You can get these from the Firebase Console Project Settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR-iVzjUqDtg3BUSMqQfIwn0qReaRrKBY',
    appId: '1:285253284489:web:458ec93ef1f70bbeb28c58',
    messagingSenderId: '285253284489',
    projectId: 'hompimpapos',
    authDomain: 'hompimpapos.firebaseapp.com',
    storageBucket: 'hompimpapos.firebasestorage.app',
    measurementId: 'G-CQBXSZ278H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIwAC4C5PD-oT-VMcbR7AD-g_yFglBUd0',
    appId: '1:285253284489:android:acedd6c55e96fa40b28c58',
    messagingSenderId: '285253284489',
    projectId: 'hompimpapos',
    storageBucket: 'hompimpapos.firebasestorage.app',
  );
}
